const CREATE_DECK = 'CREATE_DECK';
const CREATE_DECK_SUCCESS = 'CREATE_DECK_SUCCESS';
const CREATE_DECK_FAILURE = 'CREATE_DECK_FAILURE';

export { CREATE_DECK, CREATE_DECK_SUCCESS, CREATE_DECK_FAILURE };
