const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK';
const ADD_CARD_TO_DECK_SUCCESS = 'ADD_CARD_TO_DECK_SUCCESS';
const ADD_CARD_TO_DECK_FAILURE = 'ADD_CARD_TO_DECK_FAILURE';

export { ADD_CARD_TO_DECK, ADD_CARD_TO_DECK_SUCCESS, ADD_CARD_TO_DECK_FAILURE };
